import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { RitimAnalytics } from "./_components/ritim-analytics";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Demo Ritim Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <menu 
      className={`mx-auto underline w-80 h-20 p-4 space-x-4`}>
          <Link href="/">Home</Link>
          <Link href="/blog">Blogs</Link>
        </menu>
        {children}
        <RitimAnalytics />
      </body>
    </html>
  );
}
